### ISSUE TITLE
Dependencies conflict on Debian 8

### ISSUE THREAD

**Issue by AdrianEunoia** [bcollazo/dejavu#8]
Hey there!
Im just trying this on debian 8, but at the momment of installing with `pip install -e git+https://github.com/bcollazo/dejavu@v1.2#egg=PyDejavu` I get these errors about pkg-resources.

The errors I talk about :

> Could not find a version that satisfies the requirement pkg-resources==0.0.0 (from PyDejavu) (from versions: ) No matching distribution found for pkg-resources==0.0.0 (from PyDejavu)

Img attached.

**Comment by bcollazo** [comment]
Hmm, don't have too much experience with that OS, but that seems related to the well known pkg-resources==0.0.0 bug. https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command

Weird, since we don't have that line in our requirements.txt. Could you try cloning the repo and `pip install -r requirements.txt` and see where that leads? Could you use it like that?

**Comment by bcollazo** [comment]
Feel free to reopen if someone else experiences this.
